
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const Button: typeof import("../components/Button.vue")['default']
export const Changelog: typeof import("../components/Changelog.vue")['default']
export const Collapse: typeof import("../components/Collapse.vue")['default']
export const ConfigTitle: typeof import("../components/ConfigTitle.vue")['default']
export const ConnectForm: typeof import("../components/ConnectForm.vue")['default']
export const ConnectionErrorBanner: typeof import("../components/ConnectionErrorBanner.vue")['default']
export const ConnectivityBoard: typeof import("../components/ConnectivityBoard.vue")['default']
export const DataTable: typeof import("../components/DataTable.vue")['default']
export const DesktopSettingsPanel: typeof import("../components/DesktopSettingsPanel.vue")['default']
export const GlobalTrafficIndicator: typeof import("../components/GlobalTrafficIndicator.vue")['default']
export const HighchartsAutoSize: typeof import("../components/HighchartsAutoSize.vue")['default']
export const IPInfoCard: typeof import("../components/IPInfoCard.vue")['default']
export const IconMenuSelect: typeof import("../components/IconMenuSelect.vue")['default']
export const KernelControlPanel: typeof import("../components/KernelControlPanel.vue")['default']
export const KernelLogView: typeof import("../components/KernelLogView.vue")['default']
export const KernelVersionPanel: typeof import("../components/KernelVersionPanel.vue")['default']
export const LangSwitcher: typeof import("../components/LangSwitcher.vue")['default']
export const Latency: typeof import("../components/Latency.vue")['default']
export const LatencyCard: typeof import("../components/LatencyCard.vue")['default']
export const LogoText: typeof import("../components/LogoText.vue")['default']
export const Marquee: typeof import("../components/Marquee.vue")['default']
export const MobileBottomNav: typeof import("../components/MobileBottomNav.vue")['default']
export const Modal: typeof import("../components/Modal.vue")['default']
export const MonacoYamlEditor: typeof import("../components/MonacoYamlEditor.client.vue")['default']
export const NetworkConfigPanel: typeof import("../components/NetworkConfigPanel.vue")['default']
export const NetworkTopology: typeof import("../components/NetworkTopology.vue")['default']
export const OnboardingEmptyState: typeof import("../components/OnboardingEmptyState.vue")['default']
export const OnboardingWizard: typeof import("../components/OnboardingWizard.vue")['default']
export const ProfileImportHero: typeof import("../components/ProfileImportHero.vue")['default']
export const ProtectedResources: typeof import("../components/ProtectedResources.vue")['default']
export const ProxiesCardSizeSelect: typeof import("../components/ProxiesCardSizeSelect.vue")['default']
export const ProxiesDisplayModeSwitcher: typeof import("../components/ProxiesDisplayModeSwitcher.vue")['default']
export const ProxiesRenderWrapper: typeof import("../components/ProxiesRenderWrapper.vue")['default']
export const ProxiesSortSelect: typeof import("../components/ProxiesSortSelect.vue")['default']
export const ProxyConfigEditor: typeof import("../components/ProxyConfigEditor.vue")['default']
export const ProxyMasterDetail: typeof import("../components/ProxyMasterDetail.vue")['default']
export const ProxyNodeCard: typeof import("../components/ProxyNodeCard.vue")['default']
export const ProxyNodeListItem: typeof import("../components/ProxyNodeListItem.vue")['default']
export const ProxyNodeName: typeof import("../components/ProxyNodeName.vue")['default']
export const ProxyNodePreview: typeof import("../components/ProxyNodePreview.vue")['default']
export const ProxyNodeTableRow: typeof import("../components/ProxyNodeTableRow.vue")['default']
export const ProxyNodeTooltip: typeof import("../components/ProxyNodeTooltip.vue")['default']
export const ProxyPreviewBar: typeof import("../components/ProxyPreviewBar.vue")['default']
export const ProxyPreviewDots: typeof import("../components/ProxyPreviewDots.vue")['default']
export const PwaUpdatePrompt: typeof import("../components/PwaUpdatePrompt.client.vue")['default']
export const RealtimeLineChart: typeof import("../components/RealtimeLineChart.vue")['default']
export const RuntimeConfigPanel: typeof import("../components/RuntimeConfigPanel.vue")['default']
export const ShortcutsHelpModal: typeof import("../components/ShortcutsHelpModal.vue")['default']
export const ShortcutsSettings: typeof import("../components/ShortcutsSettings.vue")['default']
export const Sidebar: typeof import("../components/Sidebar.vue")['default']
export const SubscriptionInfo: typeof import("../components/SubscriptionInfo.vue")['default']
export const SubscriptionUsageCard: typeof import("../components/SubscriptionUsageCard.vue")['default']
export const SystemProxyControlPanel: typeof import("../components/SystemProxyControlPanel.vue")['default']
export const ThemeList: typeof import("../components/ThemeList.vue")['default']
export const ThemeSelector: typeof import("../components/ThemeSelector.vue")['default']
export const ThemeSwitcher: typeof import("../components/ThemeSwitcher.vue")['default']
export const TitleBar: typeof import("../components/TitleBar.vue")['default']
export const TrafficDetailsTable: typeof import("../components/TrafficDetailsTable.vue")['default']
export const TrafficRankings: typeof import("../components/TrafficRankings.vue")['default']
export const TrafficTrendChart: typeof import("../components/TrafficTrendChart.vue")['default']
export const TrafficWidget: typeof import("../components/TrafficWidget.vue")['default']
export const Versions: typeof import("../components/Versions.vue")['default']
export const WebdavBackupPanel: typeof import("../components/WebdavBackupPanel.vue")['default']
export const SchemaValueEditor: typeof import("../components/config-editor/SchemaValueEditor.vue")['default']
export const ConnectionDetailsModal: typeof import("../components/connections/ConnectionDetailsModal.vue")['default']
export const ConnectionsPagination: typeof import("../components/connections/ConnectionsPagination.vue")['default']
export const ConnectionsSettingsModal: typeof import("../components/connections/ConnectionsSettingsModal.vue")['default']
export const ConnectionsTable: typeof import("../components/connections/ConnectionsTable.vue")['default']
export const ConnectionsToolbar: typeof import("../components/connections/ConnectionsToolbar.vue")['default']
export const ColumnSortable: typeof import("../components/connections/columnSortable")['default']
export const ConnectionsExport: typeof import("../components/connections/connectionsExport")['default']
export const GlobalFilter: typeof import("../components/connections/globalFilter")['default']
export const Connections: typeof import("../components/connections/index")['default']
export const QuickFilter: typeof import("../components/connections/quickFilter")['default']
export const NuxtWelcome: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtLinkLocale: typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@10.6.0_@vue+co_b35280b912ccf8be318d4ded2707e145/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@10.6.0_@vue+co_b35280b912ccf8be318d4ded2707e145/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const VitePwaManifest: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaManifest: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaAssets: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const PwaAppleImage: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleImage")['default']
export const PwaAppleSplashScreenImage: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleSplashScreenImage")['default']
export const PwaFaviconImage: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaFaviconImage")['default']
export const PwaMaskableImage: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaMaskableImage")['default']
export const PwaTransparentImage: typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaTransparentImage")['default']
export const NuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyButton: LazyComponent<typeof import("../components/Button.vue")['default']>
export const LazyChangelog: LazyComponent<typeof import("../components/Changelog.vue")['default']>
export const LazyCollapse: LazyComponent<typeof import("../components/Collapse.vue")['default']>
export const LazyConfigTitle: LazyComponent<typeof import("../components/ConfigTitle.vue")['default']>
export const LazyConnectForm: LazyComponent<typeof import("../components/ConnectForm.vue")['default']>
export const LazyConnectionErrorBanner: LazyComponent<typeof import("../components/ConnectionErrorBanner.vue")['default']>
export const LazyConnectivityBoard: LazyComponent<typeof import("../components/ConnectivityBoard.vue")['default']>
export const LazyDataTable: LazyComponent<typeof import("../components/DataTable.vue")['default']>
export const LazyDesktopSettingsPanel: LazyComponent<typeof import("../components/DesktopSettingsPanel.vue")['default']>
export const LazyGlobalTrafficIndicator: LazyComponent<typeof import("../components/GlobalTrafficIndicator.vue")['default']>
export const LazyHighchartsAutoSize: LazyComponent<typeof import("../components/HighchartsAutoSize.vue")['default']>
export const LazyIPInfoCard: LazyComponent<typeof import("../components/IPInfoCard.vue")['default']>
export const LazyIconMenuSelect: LazyComponent<typeof import("../components/IconMenuSelect.vue")['default']>
export const LazyKernelControlPanel: LazyComponent<typeof import("../components/KernelControlPanel.vue")['default']>
export const LazyKernelLogView: LazyComponent<typeof import("../components/KernelLogView.vue")['default']>
export const LazyKernelVersionPanel: LazyComponent<typeof import("../components/KernelVersionPanel.vue")['default']>
export const LazyLangSwitcher: LazyComponent<typeof import("../components/LangSwitcher.vue")['default']>
export const LazyLatency: LazyComponent<typeof import("../components/Latency.vue")['default']>
export const LazyLatencyCard: LazyComponent<typeof import("../components/LatencyCard.vue")['default']>
export const LazyLogoText: LazyComponent<typeof import("../components/LogoText.vue")['default']>
export const LazyMarquee: LazyComponent<typeof import("../components/Marquee.vue")['default']>
export const LazyMobileBottomNav: LazyComponent<typeof import("../components/MobileBottomNav.vue")['default']>
export const LazyModal: LazyComponent<typeof import("../components/Modal.vue")['default']>
export const LazyMonacoYamlEditor: LazyComponent<typeof import("../components/MonacoYamlEditor.client.vue")['default']>
export const LazyNetworkConfigPanel: LazyComponent<typeof import("../components/NetworkConfigPanel.vue")['default']>
export const LazyNetworkTopology: LazyComponent<typeof import("../components/NetworkTopology.vue")['default']>
export const LazyOnboardingEmptyState: LazyComponent<typeof import("../components/OnboardingEmptyState.vue")['default']>
export const LazyOnboardingWizard: LazyComponent<typeof import("../components/OnboardingWizard.vue")['default']>
export const LazyProfileImportHero: LazyComponent<typeof import("../components/ProfileImportHero.vue")['default']>
export const LazyProtectedResources: LazyComponent<typeof import("../components/ProtectedResources.vue")['default']>
export const LazyProxiesCardSizeSelect: LazyComponent<typeof import("../components/ProxiesCardSizeSelect.vue")['default']>
export const LazyProxiesDisplayModeSwitcher: LazyComponent<typeof import("../components/ProxiesDisplayModeSwitcher.vue")['default']>
export const LazyProxiesRenderWrapper: LazyComponent<typeof import("../components/ProxiesRenderWrapper.vue")['default']>
export const LazyProxiesSortSelect: LazyComponent<typeof import("../components/ProxiesSortSelect.vue")['default']>
export const LazyProxyConfigEditor: LazyComponent<typeof import("../components/ProxyConfigEditor.vue")['default']>
export const LazyProxyMasterDetail: LazyComponent<typeof import("../components/ProxyMasterDetail.vue")['default']>
export const LazyProxyNodeCard: LazyComponent<typeof import("../components/ProxyNodeCard.vue")['default']>
export const LazyProxyNodeListItem: LazyComponent<typeof import("../components/ProxyNodeListItem.vue")['default']>
export const LazyProxyNodeName: LazyComponent<typeof import("../components/ProxyNodeName.vue")['default']>
export const LazyProxyNodePreview: LazyComponent<typeof import("../components/ProxyNodePreview.vue")['default']>
export const LazyProxyNodeTableRow: LazyComponent<typeof import("../components/ProxyNodeTableRow.vue")['default']>
export const LazyProxyNodeTooltip: LazyComponent<typeof import("../components/ProxyNodeTooltip.vue")['default']>
export const LazyProxyPreviewBar: LazyComponent<typeof import("../components/ProxyPreviewBar.vue")['default']>
export const LazyProxyPreviewDots: LazyComponent<typeof import("../components/ProxyPreviewDots.vue")['default']>
export const LazyPwaUpdatePrompt: LazyComponent<typeof import("../components/PwaUpdatePrompt.client.vue")['default']>
export const LazyRealtimeLineChart: LazyComponent<typeof import("../components/RealtimeLineChart.vue")['default']>
export const LazyRuntimeConfigPanel: LazyComponent<typeof import("../components/RuntimeConfigPanel.vue")['default']>
export const LazyShortcutsHelpModal: LazyComponent<typeof import("../components/ShortcutsHelpModal.vue")['default']>
export const LazyShortcutsSettings: LazyComponent<typeof import("../components/ShortcutsSettings.vue")['default']>
export const LazySidebar: LazyComponent<typeof import("../components/Sidebar.vue")['default']>
export const LazySubscriptionInfo: LazyComponent<typeof import("../components/SubscriptionInfo.vue")['default']>
export const LazySubscriptionUsageCard: LazyComponent<typeof import("../components/SubscriptionUsageCard.vue")['default']>
export const LazySystemProxyControlPanel: LazyComponent<typeof import("../components/SystemProxyControlPanel.vue")['default']>
export const LazyThemeList: LazyComponent<typeof import("../components/ThemeList.vue")['default']>
export const LazyThemeSelector: LazyComponent<typeof import("../components/ThemeSelector.vue")['default']>
export const LazyThemeSwitcher: LazyComponent<typeof import("../components/ThemeSwitcher.vue")['default']>
export const LazyTitleBar: LazyComponent<typeof import("../components/TitleBar.vue")['default']>
export const LazyTrafficDetailsTable: LazyComponent<typeof import("../components/TrafficDetailsTable.vue")['default']>
export const LazyTrafficRankings: LazyComponent<typeof import("../components/TrafficRankings.vue")['default']>
export const LazyTrafficTrendChart: LazyComponent<typeof import("../components/TrafficTrendChart.vue")['default']>
export const LazyTrafficWidget: LazyComponent<typeof import("../components/TrafficWidget.vue")['default']>
export const LazyVersions: LazyComponent<typeof import("../components/Versions.vue")['default']>
export const LazyWebdavBackupPanel: LazyComponent<typeof import("../components/WebdavBackupPanel.vue")['default']>
export const LazySchemaValueEditor: LazyComponent<typeof import("../components/config-editor/SchemaValueEditor.vue")['default']>
export const LazyConnectionDetailsModal: LazyComponent<typeof import("../components/connections/ConnectionDetailsModal.vue")['default']>
export const LazyConnectionsPagination: LazyComponent<typeof import("../components/connections/ConnectionsPagination.vue")['default']>
export const LazyConnectionsSettingsModal: LazyComponent<typeof import("../components/connections/ConnectionsSettingsModal.vue")['default']>
export const LazyConnectionsTable: LazyComponent<typeof import("../components/connections/ConnectionsTable.vue")['default']>
export const LazyConnectionsToolbar: LazyComponent<typeof import("../components/connections/ConnectionsToolbar.vue")['default']>
export const LazyColumnSortable: LazyComponent<typeof import("../components/connections/columnSortable")['default']>
export const LazyConnectionsExport: LazyComponent<typeof import("../components/connections/connectionsExport")['default']>
export const LazyGlobalFilter: LazyComponent<typeof import("../components/connections/globalFilter")['default']>
export const LazyConnections: LazyComponent<typeof import("../components/connections/index")['default']>
export const LazyQuickFilter: LazyComponent<typeof import("../components/connections/quickFilter")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtLinkLocale: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@10.6.0_@vue+co_b35280b912ccf8be318d4ded2707e145/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
export const LazySwitchLocalePathLink: LazyComponent<typeof import("../../../node_modules/.pnpm/@nuxtjs+i18n@10.6.0_@vue+co_b35280b912ccf8be318d4ded2707e145/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
export const LazyVitePwaManifest: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
export const LazyNuxtPwaManifest: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
export const LazyNuxtPwaAssets: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']>
export const LazyPwaAppleImage: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleImage")['default']>
export const LazyPwaAppleSplashScreenImage: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleSplashScreenImage")['default']>
export const LazyPwaFaviconImage: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaFaviconImage")['default']>
export const LazyPwaMaskableImage: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaMaskableImage")['default']>
export const LazyPwaTransparentImage: LazyComponent<typeof import("../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaTransparentImage")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
