export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptVercelAnalytics, useScriptPostHog, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptMixpanelAnalytics, useScriptBingUet, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptGoogleRecaptcha, useScriptGoogleSignIn, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptTikTokPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal, useScriptGravatar, useScriptAhrefsAnalytics, useScriptLinkedInInsight, useScriptCalendly, useScriptUsercentrics, useScriptSpeedCurve } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData, createUseAsyncData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch, createUseFetch } from '#app/composables/fetch';
export { $fetch } from '#build/fetch.mjs';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useLayout } from '#app/composables/layout';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useAnnouncer } from '#app/composables/announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, useCssVars, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { computedAsync, asyncComputed, computedEager, eagerComputed, computedInject, computedWithControl, controlledComputed, createDisposableDirective, createEventHook, createGlobalState, createInjectionState, createRef, createReusableTemplate, createSharedComposable, createTemplatePromise, createUnrefFn, extendRef, injectLocal, isDefined, makeDestructurable, onClickOutside, onElementRemoval, onKeyStroke, onKeyDown, onKeyUp, onKeyPressed, onLongPress, onStartTyping, provideLocal, reactify, createReactiveFn, reactifyObject, reactiveComputed, reactiveOmit, reactivePick, refAutoReset, autoResetRef, refDebounced, useDebounce, debouncedRef, refDefault, refManualReset, refThrottled, useThrottle, throttledRef, refWithControl, controlledRef, syncRef, syncRefs, templateRef, toReactive, tryOnBeforeMount, tryOnBeforeUnmount, tryOnMounted, tryOnScopeDispose, tryOnUnmounted, unrefElement, until, useActiveElement, useAnimate, useArrayDifference, useArrayEvery, useArrayFilter, useArrayFind, useArrayFindIndex, useArrayFindLast, useArrayIncludes, useArrayJoin, useArrayMap, useArrayReduce, useArraySome, useArrayUnique, useAsyncQueue, useAsyncState, useBase64, useBattery, useBluetooth, useBreakpoints, useBroadcastChannel, useBrowserLocation, useCached, useClipboard, useClipboardItems, useCloned, useColorMode, useConfirmDialog, useCountdown, useCounter, useCssSupports, useCssVar, useCurrentElement, useCycleList, useDark, useDateFormat, useDebouncedRefHistory, useDebounceFn, useDeviceMotion, useDeviceOrientation, useDevicePixelRatio, useDevicesList, useDisplayMedia, useDocumentVisibility, useDraggable, useDropZone, useElementBounding, useElementByPoint, useElementHover, useElementOverflow, useElementSize, useElementVisibility, useEventBus, useEventListener, useEventSource, useEyeDropper, useFavicon, useFileDialog, useFileSystemAccess, useFocus, useFocusWithin, useFps, useFullscreen, useGamepad, useGeolocation, useIdle, useInfiniteScroll, useIntersectionObserver, useInterval, useIntervalFn, useKeyModifier, useLastChanged, useLocalStorage, useMagicKeys, useManualRefHistory, useMediaControls, useMediaQuery, useMemoize, useMemory, useMounted, useMouse, useMouseInElement, useMousePressed, useMutationObserver, useNavigatorLanguage, useNetwork, useNow, useObjectUrl, useOffsetPagination, useOnline, usePageLeave, useParallax, useParentElement, usePerformanceObserver, usePermission, usePointer, usePointerLock, usePointerSwipe, usePreferredColorScheme, usePreferredContrast, usePreferredDark, usePreferredLanguages, usePreferredReducedMotion, usePreferredReducedTransparency, usePrevious, useRafFn, useRefHistory, useResizeObserver, useScreenOrientation, useScreenSafeArea, useScriptTag, useScroll, useScrollLock, useSessionStorage, useShare, useSorted, useSpeechRecognition, useSpeechSynthesis, useSSRWidth, useStepper, useStorageAsync, useStyleTag, useSupported, useSwipe, useTemplateRefsList, useTextareaAutosize, useTextDirection, useTextSelection, useThrottledRefHistory, useThrottleFn, useTimeAgo, formatTimeAgo, useTimeAgoIntl, formatTimeAgoIntl, useTimeout, useTimeoutFn, useTimeoutPoll, useTimestamp, useTitle, useToggle, useToNumber, useToString, useTransition, useUrlSearchParams, useUserMedia, useVibrate, useVirtualList, useVModel, useVModels, useWakeLock, useWebNotification, useWebSocket, useWebWorker, useWebWorkerFn, useWindowFocus, useWindowScroll, useWindowSize, watchArray, watchAtMost, watchDebounced, debouncedWatch, watchDeep, watchIgnorable, ignorableWatch, watchImmediate, watchOnce, watchPausable, pausableWatch, watchThrottled, throttledWatch, watchTriggerable, watchWithFilter, whenever } from '@vueuse/core';
export { useRouteBaseName, useLocalePath, useLocaleRoute, useSwitchLocalePath, useLocaleHead, useBrowserLocale, useCookieLocale, useSetI18nParams, useI18nPreloadKeys, defineI18nRoute, defineI18nLocale, defineI18nConfig } from '../../../node_modules/.pnpm/@nuxtjs+i18n@10.6.0_@vue+co_b35280b912ccf8be318d4ded2707e145/node_modules/@nuxtjs/i18n/dist/runtime/composables/index';
export { definePageMeta, PageMeta } from '#app/composables/pages';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useActiveProfileEditor, ActiveProfileEditorLoadResult, ActiveProfileEditorSaveResult } from '../composables/useActiveProfileEditor';
export { useMockMode, useRequest, useGithubAPI, checkEndpointAPI, closeAllConnectionsAPI, closeSingleConnectionAPI, fetchBackendConfigAPI, updateBackendConfigAPI, fetchBackendVersionAPI, fetchProxyProvidersAPI, fetchProxiesAPI, updateProxyProviderAPI, proxyProviderHealthCheckAPI, selectProxyInGroupAPI, unfixProxyInGroupAPI, proxyLatencyTestAPI, proxyGroupLatencyTestAPI, fetchRulesAPI, fetchRuleProvidersAPI, updateRuleProviderAPI, toggleRuleDisabledAPI, useConfigActions, frontendReleaseAPI, backendReleaseAPI, fetchFrontendReleasesAPI, fetchBackendReleasesAPI, EndpointCheckError } from '../composables/useApi';
export { CUSTOM_THEME_TOKENS, useAppearance } from '../composables/useAppearance';
export { useBatchLatencyTest, BatchTestOptions } from '../composables/useBatchLatencyTest';
export { useBusyKeys } from '../composables/useBusyKeys';
export { useConnect } from '../composables/useConnect';
export { resolveControlConfig, useControlApi, ControlConfig } from '../composables/useControlApi';
export { useControlInfo } from '../composables/useControlInfo';
export { onControlInvalidate } from '../composables/useControlSync';
export { CUSTOM_CSS_STYLE_ID, applyCustomCss, useCustomCss } from '../composables/useCustomCss';
export { useDataTable, UseDataTableOptions } from '../composables/useDataTable';
export { useDataUsage, AggregatedData } from '../composables/useDataUsage';
export { useDesktop, DesktopWindowControls, DesktopShellSettings, DesktopSettingsBridge, DesktopHotkeysPayload, DesktopHotkeysBridge } from '../composables/useDesktop';
export { useDnsSettings, DnsPayload, DnsSettingsMutation } from '../composables/useDnsSettings';
export { PORT_FIELDS, useGeneralConfig, GeneralConfigMutation, UseGeneralConfigOptions } from '../composables/useGeneralConfig';
export { useGeoAssets } from '../composables/useGeoAssets';
export { countryCodeToFlagEmoji, isPrivateOrReservedIP, useGeoLookup, GeoInfo } from '../composables/useGeoLookup';
export { loadHighcharts } from '../composables/useHighcharts';
export { fetchIPInfo, useIPInfo } from '../composables/useIPInfo';
export { useKernelVersions } from '../composables/useKernelVersions';
export { useKeyboardShortcuts } from '../composables/useKeyboardShortcuts';
export { useLatencyTest } from '../composables/useLatencyTest';
export { useMenuKeyboard, MenuKeyboardOptions } from '../composables/useMenuKeyboard';
export { mockVersion, mockConfig, mockProxies, mockProxyProviders, mockRules, mockRuleProviders, mockConnections, mockLogs, mockTrafficStats, mockMemory, useMockData } from '../composables/useMockData';
export { useNetworkConfig, TunnelEntry } from '../composables/useNetworkConfig';
export { useProfileStatus } from '../composables/useProfileStatus';
export { useProfiles } from '../composables/useProfiles';
export { useProxyConfigEditor, RoutingResourceDraft } from '../composables/useProxyConfigEditor';
export { useProxyNode, UseProxyNodeOptions } from '../composables/useProxyNode';
export { queryKeys, useEndpointScopedKey, useProxiesQuery, useProxyProvidersQuery, useSelectProxyMutation, useProxyLatencyTestMutation, useProxyGroupLatencyTestMutation, useUpdateProxyProviderMutation, useProxyProviderHealthCheckMutation, useRulesQuery, useToggleRuleDisabledMutation, useRuleProvidersQuery, useUpdateRuleProviderMutation, useConfigQuery, applyConfigPatch, useUpdateConfigMutation, useVersionQuery, useCloseConnectionMutation, useCloseAllConnectionsMutation, useReloadConfigMutation, useFlushFakeIPMutation, useFlushDNSCacheMutation, useUpdateGEOMutation, useUpgradeBackendMutation, useUpgradeUIMutation, useRestartBackendMutation } from '../composables/useQueries';
export { CONNECTIVITY_TARGETS, STREAMING_UNLOCK_TARGETS, useReachabilityBoard, ReachabilityTarget, ReachabilityResult, ReachabilityTestOptions } from '../composables/useReachabilityBoard';
export { isResolvableIP, reverseName, useReverseDns } from '../composables/useReverseDns';
export { useRuleEditor } from '../composables/useRuleEditor';
export { useRuntimeConfigViewer } from '../composables/useRuntimeConfigViewer';
export { useSettingsBackup, SettingsBackup } from '../composables/useSettingsBackup';
export { useShareQr } from '../composables/useShareQr';
export { acquireSingletonPopover, releaseSingletonPopover } from '../composables/useSingletonPopover';
export { useSystemProxy } from '../composables/useSystemProxy';
export { useTun } from '../composables/useTun';
export { useTunConfig, TunConfigOptions } from '../composables/useTunConfig';
export { useBackendWebSocket } from '../composables/useWebSocket';
export { useWebdavBackup } from '../composables/useWebdavBackup';
export { useWindowControls } from '../composables/useWindowControls';
export { saveBackgroundImage, loadBackgroundImage, clearBackgroundImage } from '../utils/appearanceDb';
export { resolveConfigSchema, configSectionSchema, configGeneralKeys, defaultForSchema, ConfigJsonSchema } from '../utils/configSchema';
export { renderTwoLineCell } from '../utils/connectionCells';
export { controlErrorMessage } from '../utils/controlError';
export { DataUsageDB, db, DataUsageLog } from '../utils/db';
export { compareVersions, isSingBoxVersion, formatBytes, transformEndpointURL, randomUUID, formatIPv6, formatTimeFromNow, formatDuration, formatDateRange, formatProxyType, orderProxyModes, classifyLatency, getLatencyClassName, filterSpecialProxyType, sortProxiesByOrderingType, filterProxiesByAvailability, filterProxiesByName, REGION_OTHER, codeToFlag, parseNodeRegion, getRegionFacets, filterNodesByRegion, getTypeFacets, filterNodesByType, getCapabilityFacets, filterNodesByCapability, splitLeadingFlag, gapLeadingFlag, getRuleFacets, filterRules, sortRulesByOrderingType, useStringBooleanMap, fuzzyFilter, getThemeColors, getChartThemeColors, encodeSvg, resolveActiveGroup, LatencyBand, RegionFacet, TypeFacet, CapabilityFacet, RuleFacet } from '../utils/index';
export { computeLatencyTrend, svgPathFromPoints, LatencyTrend } from '../utils/latencyTrend';
export { ensureMonacoYaml } from '../utils/monaco-setup';
export { DEFAULT_SCORING_WEIGHTS, SCORE_THRESHOLDS, calculateLatencyScore, calculateStabilityScore, calculateSuccessRateScore, calculateNodeScore, getScoreColorClass, getScoreBgClass, formatTimeSince, findRecommendedNode } from '../utils/nodeScoring';
export { PROXY_TYPES, PROXY_GROUP_TYPES, PROXY_PROTOCOL_FIELDS, BOOLEAN_ROUTING_FIELDS, NUMBER_ROUTING_FIELDS, routingResourceFields, isSensitiveRoutingField } from '../utils/routingResources';
export { useConfigStore } from '../stores/config';
export { useConnectionsStore } from '../stores/connections';
export { useEndpointStore } from '../stores/endpoint';
export { useGlobalStore } from '../stores/global';
export { useKernelStore, KernelLogLine } from '../stores/kernel';
export { useLogsStore } from '../stores/logs';
export { useNodeRecommendationStore, NodePerformanceEntry, NodePerformanceData, ScoringWeights, BatchTestProgress } from '../stores/nodeRecommendation';
export { useProxiesStore, ProxyNodeView } from '../stores/proxies';
export { useRulesStore } from '../stores/rules';
export { useShortcutsStore } from '../stores/shortcuts';
export { themes, FALLBACK_BACKEND_URL, DEFAULT_SCRIPT_CONTENT, ROUTES, MOBILE_NAV_RESELECT_EVENT, CHART_MAX_XAXIS, LATENCY_QUALITY_MAP_HTTP, LATENCY_QUALITY_MAP_HTTPS, PROXIES_PREVIEW_TYPE, PROXIES_ORDERING_TYPE, PROXIES_ORDERING_TYPE_ORDER, RULES_ORDERING_TYPE, RULES_ORDERING_TYPE_ORDER, PROXIES_DISPLAY_MODE, PROXIES_DISPLAY_MODE_ORDER, PROXIES_CARD_SIZE, PROXIES_CARD_SIZE_MIN_WIDTH, PROXIES_CARD_SIZE_GAP, CONNECTIONS_TABLE_ACCESSOR_KEY, CONNECTIONS_TABLE_MAX_CLOSED_ROWS, CONNECTIONS_TABLE_INITIAL_COLUMN_ORDER, CONNECTIONS_TABLE_INITIAL_COLUMN_VISIBILITY, TAILWINDCSS_SIZE, LOG_LEVEL, LOGS_TABLE_MAX_ROWS_LIST, MobileNavReselectDetail } from '../constants/index';
export { DEFAULT_SHORTCUTS, SHORTCUT_CATEGORIES, SHORTCUT_LABELS, formatShortcutKey, ShortcutAction, ShortcutConfig, ShortcutCategory } from '../constants/shortcuts';
export { KernelStatus, KernelState, ProfileType, ProfileSubscriptionInfo, ProfileMeta, ControlFeature, ProfileEditorSnapshot, ProfileEditorPreview, ControlInfo, ControlLogEvent, ProfileDetail, ValidateResult, SystemProxyState, KernelVersions, GeoUpdateResult, WebdavCredentials, WebdavBackupResult, WebdavRestoreResult, TunStatus } from '../types/control';
export { Proxy, ProxyNode, SubscriptionInfo, ProxyProvider, RuleExtra, Rule, RuleProvider, ConnectionRawMessage, Connection, Log, LogWithSeq, Config, DNSQuery, BackendVersion, ConnectionsTableColumnVisibility, ConnectionsTableColumnOrder, DataUsageType, DataUsageEntry, TrafficData, MemoryData, WsMsg, ChartDataPoint, Endpoint, ProxyWithProvider, ProxyNodeWithProvider, ReleaseInfo } from '../types/index';
export { IPSBResponse, IPWhoIsResponse, IPAPIResponse, IPInfo, IPProvider, LatencyResult, TopologyNode, TopologyEdge } from '../types/network';
export { defineStore, acceptHMRUpdate, usePinia, storeToRefs } from '../../../node_modules/.pnpm/@pinia+nuxt@1.0.2_magic-str_fa3f69a77aa12c1d935ecdc5073fd4f3/node_modules/@pinia/nuxt/dist/runtime/composables';
export { useI18n } from 'vue-i18n';
export { usePWA, useTransparentPwaIcon, useMaskablePwaIcon, useFaviconPwaIcon, useApplePwaIcon, useAppleSplashScreenPwaIcon } from '../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/composables/index';
export { useNuxtDevTools } from '../../../node_modules/.pnpm/@nuxt+devtools@3.4.1_db0@0._fe45274267bb252cd9dc305ef2c4ee19/node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools';