minimumReleaseAge: 10080

packages:
  - '.'
  - 'packages/agent'
  - 'packages/config-editor'

catalog:
  '@types/node': ^26.1.2
  h3: ^1.15.4
  tree-kill: ^1.2.2
  typescript: ^6.0.3
  vitest: ^3.2.4
  yaml: ^2.9.0

allowBuilds:
  '@bufbuild/buf': true
  esbuild: true
