// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/plugins/unhead.server.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/plugins/unhead.client.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/plugins/router.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/@nuxt+devtools@3.4.1_db0@0._fe45274267bb252cd9dc305ef2c4ee19/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/@nuxt+devtools@3.4.1_db0@0._fe45274267bb252cd9dc305ef2c4ee19/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:global-components' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
