
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  Button: typeof import("../../components/Button.vue")['default']
  Changelog: typeof import("../../components/Changelog.vue")['default']
  Collapse: typeof import("../../components/Collapse.vue")['default']
  ConfigTitle: typeof import("../../components/ConfigTitle.vue")['default']
  ConnectForm: typeof import("../../components/ConnectForm.vue")['default']
  ConnectionErrorBanner: typeof import("../../components/ConnectionErrorBanner.vue")['default']
  ConnectivityBoard: typeof import("../../components/ConnectivityBoard.vue")['default']
  DataTable: typeof import("../../components/DataTable.vue")['default']
  DesktopSettingsPanel: typeof import("../../components/DesktopSettingsPanel.vue")['default']
  GlobalTrafficIndicator: typeof import("../../components/GlobalTrafficIndicator.vue")['default']
  HighchartsAutoSize: typeof import("../../components/HighchartsAutoSize.vue")['default']
  IPInfoCard: typeof import("../../components/IPInfoCard.vue")['default']
  IconMenuSelect: typeof import("../../components/IconMenuSelect.vue")['default']
  KernelControlPanel: typeof import("../../components/KernelControlPanel.vue")['default']
  KernelLogView: typeof import("../../components/KernelLogView.vue")['default']
  KernelVersionPanel: typeof import("../../components/KernelVersionPanel.vue")['default']
  LangSwitcher: typeof import("../../components/LangSwitcher.vue")['default']
  Latency: typeof import("../../components/Latency.vue")['default']
  LatencyCard: typeof import("../../components/LatencyCard.vue")['default']
  LogoText: typeof import("../../components/LogoText.vue")['default']
  Marquee: typeof import("../../components/Marquee.vue")['default']
  MobileBottomNav: typeof import("../../components/MobileBottomNav.vue")['default']
  Modal: typeof import("../../components/Modal.vue")['default']
  MonacoYamlEditor: typeof import("../../components/MonacoYamlEditor.client.vue")['default']
  NetworkConfigPanel: typeof import("../../components/NetworkConfigPanel.vue")['default']
  NetworkTopology: typeof import("../../components/NetworkTopology.vue")['default']
  OnboardingEmptyState: typeof import("../../components/OnboardingEmptyState.vue")['default']
  OnboardingWizard: typeof import("../../components/OnboardingWizard.vue")['default']
  ProfileImportHero: typeof import("../../components/ProfileImportHero.vue")['default']
  ProtectedResources: typeof import("../../components/ProtectedResources.vue")['default']
  ProxiesCardSizeSelect: typeof import("../../components/ProxiesCardSizeSelect.vue")['default']
  ProxiesDisplayModeSwitcher: typeof import("../../components/ProxiesDisplayModeSwitcher.vue")['default']
  ProxiesRenderWrapper: typeof import("../../components/ProxiesRenderWrapper.vue")['default']
  ProxiesSortSelect: typeof import("../../components/ProxiesSortSelect.vue")['default']
  ProxyConfigEditor: typeof import("../../components/ProxyConfigEditor.vue")['default']
  ProxyMasterDetail: typeof import("../../components/ProxyMasterDetail.vue")['default']
  ProxyNodeCard: typeof import("../../components/ProxyNodeCard.vue")['default']
  ProxyNodeListItem: typeof import("../../components/ProxyNodeListItem.vue")['default']
  ProxyNodeName: typeof import("../../components/ProxyNodeName.vue")['default']
  ProxyNodePreview: typeof import("../../components/ProxyNodePreview.vue")['default']
  ProxyNodeTableRow: typeof import("../../components/ProxyNodeTableRow.vue")['default']
  ProxyNodeTooltip: typeof import("../../components/ProxyNodeTooltip.vue")['default']
  ProxyPreviewBar: typeof import("../../components/ProxyPreviewBar.vue")['default']
  ProxyPreviewDots: typeof import("../../components/ProxyPreviewDots.vue")['default']
  PwaUpdatePrompt: typeof import("../../components/PwaUpdatePrompt.client.vue")['default']
  RealtimeLineChart: typeof import("../../components/RealtimeLineChart.vue")['default']
  RuntimeConfigPanel: typeof import("../../components/RuntimeConfigPanel.vue")['default']
  ShortcutsHelpModal: typeof import("../../components/ShortcutsHelpModal.vue")['default']
  ShortcutsSettings: typeof import("../../components/ShortcutsSettings.vue")['default']
  Sidebar: typeof import("../../components/Sidebar.vue")['default']
  SubscriptionInfo: typeof import("../../components/SubscriptionInfo.vue")['default']
  SubscriptionUsageCard: typeof import("../../components/SubscriptionUsageCard.vue")['default']
  SystemProxyControlPanel: typeof import("../../components/SystemProxyControlPanel.vue")['default']
  ThemeList: typeof import("../../components/ThemeList.vue")['default']
  ThemeSelector: typeof import("../../components/ThemeSelector.vue")['default']
  ThemeSwitcher: typeof import("../../components/ThemeSwitcher.vue")['default']
  TitleBar: typeof import("../../components/TitleBar.vue")['default']
  TrafficDetailsTable: typeof import("../../components/TrafficDetailsTable.vue")['default']
  TrafficRankings: typeof import("../../components/TrafficRankings.vue")['default']
  TrafficTrendChart: typeof import("../../components/TrafficTrendChart.vue")['default']
  TrafficWidget: typeof import("../../components/TrafficWidget.vue")['default']
  Versions: typeof import("../../components/Versions.vue")['default']
  WebdavBackupPanel: typeof import("../../components/WebdavBackupPanel.vue")['default']
  SchemaValueEditor: typeof import("../../components/config-editor/SchemaValueEditor.vue")['default']
  ConnectionDetailsModal: typeof import("../../components/connections/ConnectionDetailsModal.vue")['default']
  ConnectionsPagination: typeof import("../../components/connections/ConnectionsPagination.vue")['default']
  ConnectionsSettingsModal: typeof import("../../components/connections/ConnectionsSettingsModal.vue")['default']
  ConnectionsTable: typeof import("../../components/connections/ConnectionsTable.vue")['default']
  ConnectionsToolbar: typeof import("../../components/connections/ConnectionsToolbar.vue")['default']
  ColumnSortable: typeof import("../../components/connections/columnSortable")['default']
  ConnectionsExport: typeof import("../../components/connections/connectionsExport")['default']
  GlobalFilter: typeof import("../../components/connections/globalFilter")['default']
  Connections: typeof import("../../components/connections/index")['default']
  QuickFilter: typeof import("../../components/connections/quickFilter")['default']
  NuxtWelcome: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtAnnouncer: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
  NuxtImg: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  NuxtLinkLocale: typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.6.0_@vue+co_b35280b912ccf8be318d4ded2707e145/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
  SwitchLocalePathLink: typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.6.0_@vue+co_b35280b912ccf8be318d4ded2707e145/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
  VitePwaManifest: typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
  NuxtPwaManifest: typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
  NuxtPwaAssets: typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
  PwaAppleImage: typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleImage")['default']
  PwaAppleSplashScreenImage: typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleSplashScreenImage")['default']
  PwaFaviconImage: typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaFaviconImage")['default']
  PwaMaskableImage: typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaMaskableImage")['default']
  PwaTransparentImage: typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaTransparentImage")['default']
  NuxtPage: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyButton: LazyComponent<typeof import("../../components/Button.vue")['default']>
  LazyChangelog: LazyComponent<typeof import("../../components/Changelog.vue")['default']>
  LazyCollapse: LazyComponent<typeof import("../../components/Collapse.vue")['default']>
  LazyConfigTitle: LazyComponent<typeof import("../../components/ConfigTitle.vue")['default']>
  LazyConnectForm: LazyComponent<typeof import("../../components/ConnectForm.vue")['default']>
  LazyConnectionErrorBanner: LazyComponent<typeof import("../../components/ConnectionErrorBanner.vue")['default']>
  LazyConnectivityBoard: LazyComponent<typeof import("../../components/ConnectivityBoard.vue")['default']>
  LazyDataTable: LazyComponent<typeof import("../../components/DataTable.vue")['default']>
  LazyDesktopSettingsPanel: LazyComponent<typeof import("../../components/DesktopSettingsPanel.vue")['default']>
  LazyGlobalTrafficIndicator: LazyComponent<typeof import("../../components/GlobalTrafficIndicator.vue")['default']>
  LazyHighchartsAutoSize: LazyComponent<typeof import("../../components/HighchartsAutoSize.vue")['default']>
  LazyIPInfoCard: LazyComponent<typeof import("../../components/IPInfoCard.vue")['default']>
  LazyIconMenuSelect: LazyComponent<typeof import("../../components/IconMenuSelect.vue")['default']>
  LazyKernelControlPanel: LazyComponent<typeof import("../../components/KernelControlPanel.vue")['default']>
  LazyKernelLogView: LazyComponent<typeof import("../../components/KernelLogView.vue")['default']>
  LazyKernelVersionPanel: LazyComponent<typeof import("../../components/KernelVersionPanel.vue")['default']>
  LazyLangSwitcher: LazyComponent<typeof import("../../components/LangSwitcher.vue")['default']>
  LazyLatency: LazyComponent<typeof import("../../components/Latency.vue")['default']>
  LazyLatencyCard: LazyComponent<typeof import("../../components/LatencyCard.vue")['default']>
  LazyLogoText: LazyComponent<typeof import("../../components/LogoText.vue")['default']>
  LazyMarquee: LazyComponent<typeof import("../../components/Marquee.vue")['default']>
  LazyMobileBottomNav: LazyComponent<typeof import("../../components/MobileBottomNav.vue")['default']>
  LazyModal: LazyComponent<typeof import("../../components/Modal.vue")['default']>
  LazyMonacoYamlEditor: LazyComponent<typeof import("../../components/MonacoYamlEditor.client.vue")['default']>
  LazyNetworkConfigPanel: LazyComponent<typeof import("../../components/NetworkConfigPanel.vue")['default']>
  LazyNetworkTopology: LazyComponent<typeof import("../../components/NetworkTopology.vue")['default']>
  LazyOnboardingEmptyState: LazyComponent<typeof import("../../components/OnboardingEmptyState.vue")['default']>
  LazyOnboardingWizard: LazyComponent<typeof import("../../components/OnboardingWizard.vue")['default']>
  LazyProfileImportHero: LazyComponent<typeof import("../../components/ProfileImportHero.vue")['default']>
  LazyProtectedResources: LazyComponent<typeof import("../../components/ProtectedResources.vue")['default']>
  LazyProxiesCardSizeSelect: LazyComponent<typeof import("../../components/ProxiesCardSizeSelect.vue")['default']>
  LazyProxiesDisplayModeSwitcher: LazyComponent<typeof import("../../components/ProxiesDisplayModeSwitcher.vue")['default']>
  LazyProxiesRenderWrapper: LazyComponent<typeof import("../../components/ProxiesRenderWrapper.vue")['default']>
  LazyProxiesSortSelect: LazyComponent<typeof import("../../components/ProxiesSortSelect.vue")['default']>
  LazyProxyConfigEditor: LazyComponent<typeof import("../../components/ProxyConfigEditor.vue")['default']>
  LazyProxyMasterDetail: LazyComponent<typeof import("../../components/ProxyMasterDetail.vue")['default']>
  LazyProxyNodeCard: LazyComponent<typeof import("../../components/ProxyNodeCard.vue")['default']>
  LazyProxyNodeListItem: LazyComponent<typeof import("../../components/ProxyNodeListItem.vue")['default']>
  LazyProxyNodeName: LazyComponent<typeof import("../../components/ProxyNodeName.vue")['default']>
  LazyProxyNodePreview: LazyComponent<typeof import("../../components/ProxyNodePreview.vue")['default']>
  LazyProxyNodeTableRow: LazyComponent<typeof import("../../components/ProxyNodeTableRow.vue")['default']>
  LazyProxyNodeTooltip: LazyComponent<typeof import("../../components/ProxyNodeTooltip.vue")['default']>
  LazyProxyPreviewBar: LazyComponent<typeof import("../../components/ProxyPreviewBar.vue")['default']>
  LazyProxyPreviewDots: LazyComponent<typeof import("../../components/ProxyPreviewDots.vue")['default']>
  LazyPwaUpdatePrompt: LazyComponent<typeof import("../../components/PwaUpdatePrompt.client.vue")['default']>
  LazyRealtimeLineChart: LazyComponent<typeof import("../../components/RealtimeLineChart.vue")['default']>
  LazyRuntimeConfigPanel: LazyComponent<typeof import("../../components/RuntimeConfigPanel.vue")['default']>
  LazyShortcutsHelpModal: LazyComponent<typeof import("../../components/ShortcutsHelpModal.vue")['default']>
  LazyShortcutsSettings: LazyComponent<typeof import("../../components/ShortcutsSettings.vue")['default']>
  LazySidebar: LazyComponent<typeof import("../../components/Sidebar.vue")['default']>
  LazySubscriptionInfo: LazyComponent<typeof import("../../components/SubscriptionInfo.vue")['default']>
  LazySubscriptionUsageCard: LazyComponent<typeof import("../../components/SubscriptionUsageCard.vue")['default']>
  LazySystemProxyControlPanel: LazyComponent<typeof import("../../components/SystemProxyControlPanel.vue")['default']>
  LazyThemeList: LazyComponent<typeof import("../../components/ThemeList.vue")['default']>
  LazyThemeSelector: LazyComponent<typeof import("../../components/ThemeSelector.vue")['default']>
  LazyThemeSwitcher: LazyComponent<typeof import("../../components/ThemeSwitcher.vue")['default']>
  LazyTitleBar: LazyComponent<typeof import("../../components/TitleBar.vue")['default']>
  LazyTrafficDetailsTable: LazyComponent<typeof import("../../components/TrafficDetailsTable.vue")['default']>
  LazyTrafficRankings: LazyComponent<typeof import("../../components/TrafficRankings.vue")['default']>
  LazyTrafficTrendChart: LazyComponent<typeof import("../../components/TrafficTrendChart.vue")['default']>
  LazyTrafficWidget: LazyComponent<typeof import("../../components/TrafficWidget.vue")['default']>
  LazyVersions: LazyComponent<typeof import("../../components/Versions.vue")['default']>
  LazyWebdavBackupPanel: LazyComponent<typeof import("../../components/WebdavBackupPanel.vue")['default']>
  LazySchemaValueEditor: LazyComponent<typeof import("../../components/config-editor/SchemaValueEditor.vue")['default']>
  LazyConnectionDetailsModal: LazyComponent<typeof import("../../components/connections/ConnectionDetailsModal.vue")['default']>
  LazyConnectionsPagination: LazyComponent<typeof import("../../components/connections/ConnectionsPagination.vue")['default']>
  LazyConnectionsSettingsModal: LazyComponent<typeof import("../../components/connections/ConnectionsSettingsModal.vue")['default']>
  LazyConnectionsTable: LazyComponent<typeof import("../../components/connections/ConnectionsTable.vue")['default']>
  LazyConnectionsToolbar: LazyComponent<typeof import("../../components/connections/ConnectionsToolbar.vue")['default']>
  LazyColumnSortable: LazyComponent<typeof import("../../components/connections/columnSortable")['default']>
  LazyConnectionsExport: LazyComponent<typeof import("../../components/connections/connectionsExport")['default']>
  LazyGlobalFilter: LazyComponent<typeof import("../../components/connections/globalFilter")['default']>
  LazyConnections: LazyComponent<typeof import("../../components/connections/index")['default']>
  LazyQuickFilter: LazyComponent<typeof import("../../components/connections/quickFilter")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtAnnouncer: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyNuxtLinkLocale: LazyComponent<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.6.0_@vue+co_b35280b912ccf8be318d4ded2707e145/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
  LazySwitchLocalePathLink: LazyComponent<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.6.0_@vue+co_b35280b912ccf8be318d4ded2707e145/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
  LazyVitePwaManifest: LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
  LazyNuxtPwaManifest: LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
  LazyNuxtPwaAssets: LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']>
  LazyPwaAppleImage: LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleImage")['default']>
  LazyPwaAppleSplashScreenImage: LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaAppleSplashScreenImage")['default']>
  LazyPwaFaviconImage: LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaFaviconImage")['default']>
  LazyPwaMaskableImage: LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaMaskableImage")['default']>
  LazyPwaTransparentImage: LazyComponent<typeof import("../../../../node_modules/.pnpm/@vite-pwa+nuxt@1.1.1_magica_d726409e41b933d131c3a71a59d31506/node_modules/@vite-pwa/nuxt/dist/runtime/components/nuxt4/PwaTransparentImage")['default']>
  LazyNuxtPage: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.5.2_b1878501511ed961a289faa8d707a6e4/node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
